[versions]
kotlin = "1.9.10"
kotlinCompilerExtension = "1.5.1"
compose = "2023.08.00"
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
material3 = "1.1.1"
composeUiToolingPreview = "1.5.4"
composeUiTooling = "1.5.4"
junit = "4.13.2"
androidxJunit = "1.1.5"
espresso = "3.5.1"
sharedElements = "1.2.0-beta01"
androidxTestRunner = "1.5.2"
composeAnimation = "1.6.0"
animationAndroid = "1.7.0-alpha07"
navigationCompose = "2.7.0-alpha01"
composeUi = "1.7.0-alpha07"
coil = "2.6.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Compose BOM (Manages Compose Dependencies)
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }

# Compose UI Dependencies (Version Managed by BOM)
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUiToolingPreview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUiTooling" }

# Material Design
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

# Testing Dependencies
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }

# Shared Elements Library
compose-shared-elements = { group = "com.github.andkulikov", name = "compose-shared-elements", version.ref = "sharedElements" }

#Animation
androidx-compose-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "composeAnimation" }
androidx-animation-android = { group = "androidx.compose.animation", name = "animation-android", version.ref = "animationAndroid" }
compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animationAndroid" }

# Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Compose UI with specific version
compose-ui-versioned = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }

# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }

[plugins]
android-application = { id = "com.android.application", version = "8.2.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.10" }
